import { NEWS_CONFIG } from './config';
import { client } from '../../lib/sanity/client';

/**
 * 获取今天的文章发布数量
 */
export async function getTodayArticleCount(): Promise<number> {
  try {
    // 获取今天开始时间（UTC）
    const now = new Date();
    const startOfDay = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
    
    const query = `count(*[_type == "article" && publishedAt >= $startOfDay && source.isAutoGenerated == true])`;
    const count = await client.fetch(query, { startOfDay: startOfDay.toISOString() });
    return count || 0;
  } catch (error) {
    console.error('Failed to get today article count:', error);
    return 0;
  }
}

/**
 * 检查当前是否在发布时间段内
 * Vercel Cron 运行在 UTC 时间，需要转换为北京时间（UTC+8）
 */
export function isInPublishWindow(): boolean {
  const now = new Date();
  // 转换为北京时间（UTC+8）
  const beijingHour = (now.getUTCHours() + 8) % 24;
  const beijingMinute = now.getUTCMinutes();
  const currentTime = `${String(beijingHour).padStart(2, '0')}:${String(beijingMinute).padStart(2, '0')}`;
  
  // 允许前后5分钟的误差窗口（Cron 执行可能有延迟）
  const timeWindowMinutes = 5;
  
  for (const publishTime of NEWS_CONFIG.publish.publishTimes) {
    const [hour, minute] = publishTime.split(':').map(Number);
    const publishMinutes = hour * 60 + minute;
    const currentMinutes = beijingHour * 60 + beijingMinute;
    const diffMinutes = Math.abs(currentMinutes - publishMinutes);
    
    // 如果在时间窗口内（考虑跨天情况）
    if (diffMinutes <= timeWindowMinutes || diffMinutes >= 24 * 60 - timeWindowMinutes) {
      console.log(`✅ Within publish window: ${publishTime} (current: ${currentTime} BJT)`);
      return true;
    }
  }
  
  console.log(`⏰ Outside publish window (current: ${currentTime} BJT)`);
  return false;
}

/**
 * 检查是否应该发布文章
 * 1. 检查是否在发布时间段内
 * 2. 检查今日是否已达到发布上限
 */
export async function shouldPublish(): Promise<{ should: boolean; reason: string; remaining: number }> {
  // 检查是否在发布时间段内
  if (!isInPublishWindow()) {
    return {
      should: false,
      reason: 'Outside publish time window',
      remaining: 0,
    };
  }
  
  // 检查今日已发布数量
  const todayCount = await getTodayArticleCount();
  const maxPerDay = NEWS_CONFIG.publish.maxArticlesPerDay;
  
  if (todayCount >= maxPerDay) {
    return {
      should: false,
      reason: `Daily limit reached (${todayCount}/${maxPerDay})`,
      remaining: 0,
    };
  }
  
  return {
    should: true,
    reason: 'OK to publish',
    remaining: maxPerDay - todayCount,
  };
}

/**
 * 获取本次应该发布的文章数量
 */
export async function getPublishQuota(): Promise<number> {
  const { should, remaining } = await shouldPublish();
  if (!should) return 0;
  return remaining;
}
